### ISSUE TITLE
Back and forward buttons

### ISSUE THREAD

**Issue by dcoales** [SilentVoid13/Chesser#2]
I just decided to learn chess a couple of weeks ago and a few days ago wondered if there was any way to add images of chess boards into obsidian and immediately came across this fantastic plugin.  The universe clearly wants me to learn chess :-).

I love the fact that the boards can be interactive but would it be possible to add back and forward buttons like on lichess.com as I'm always making moves that I regret when examining opening variations and want to take moves back without resetting the entire board back to the initial FEN position.

Thanks,
David

**Comment by liamcain** [comment]
This was added in v0.2.0
