### ISSUE TITLE
FEN description line or command to copy and paste a current board position

### ISSUE THREAD

**Issue by dcoales** [SilentVoid13/Chesser#3]
I'm using this fab plugin to document and examine opening strategies.  One of the things I like to do is start with a particular position using FEN notation and then try out various variations.  If I get to a position I like I would love to be able to copy that position and paste it as another board.  Ideally this would be via a simple command to copy the current position as a FEN string so I could create a new board or alternatively an option to show the FEN string below the board (possibly next to the forward and back buttons - see my other request :-))

Thanks very much for a great plugin.

David

**Comment by liamcain** [comment]
This was added in v0.2.0
