### ISSUE TITLE
Storing positions and annotations

### ISSUE THREAD

**Issue by giorus** [SilentVoid13/Chesser#4]
If I use chesser within a note to reach a certain position on the board I lose that position whenever I move away from that note. Same issue applies to annotations i have made.

It would be great to be able to store positions and annotations for later use.

**Comment by liamcain** [comment]
This was added in v0.2.0

**Comment by Sorebit** [comment]
Are you referring to the `Copy FEN` button? Or is there a way for the plugin to automatically store the FEN when you for example save the note?
